name: Node.js CI

on:
    workflow_dispatch:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '20.x'
            - run: npm ci
            - run: npm run build
    upload:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - uses: shallwefootball/s3-upload-action@master
              with:
                  aws_key_id: ${{ secrets.AWS_KEY_ID }}
                  aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
                  aws_bucket: ${{ secrets.AWS_BUCKET }}
                  source_dir: 'build'
